allprojects {
    repositories {
        mavenCentral()
        maven { url "https://repo.grails.org/grails/core" }
    }
}

// Workaround needed for nexus publishing bug
// version and group must be specified in the root project
// https://github.com/gradle-nexus/publish-plugin/issues/310
version = projectVersion
group = 'this.will.be.overridden'

def publishedProjects = [
        'plugin',
        'gorm-testing-support'
]
subprojects {
    if (name in publishedProjects) {
        // This has to be applied here
        apply plugin: 'org.grails.grails-publish'
    }
}
