[[format]]
=== joda:format

==== Purpose

This tag formats a http://joda-time.sourceforge.net/api-release/org/joda/time/ReadableInstant.html[ReadableInstant] or http://joda-time.sourceforge.net/api-release/org/joda/time/ReadablePartial.html[ReadablePartial] instance for the page.

==== Examples

==== Description

===== Attributes

* `value` (optional) - An instance of `ReadablePartial` or `ReadableInstant` or defaults to `new DateTime()`
* `locale` (optional) - The Locale to use for formatting. Defaults to request locale
* `zone` (optional) - The `DateTimeZone` to use for formatting. Defaults to `DateTimeZone.getDefault()`
* `chronology` (optional) - The `Chronology` to use for formatting. Defaults to `ISOChronology`
* `pattern` (optional) - The pattern to use to render the date. This attribute cannot be used in conjunction with the _style_ attribute. See `DateTimeFormat` for more information.
* `style` (optional) - The style to use to render the date. Composed of two characters _"S", "M", "L"_ or _"-"_ the first representing the date portion and the last the time portion. Using _"-"_ means that portion is not output. This attribute cannot be used in conjunction with the _pattern_ attribute. Defaults to _"MM"_ for date/time values, _"M-"_ for date values or _"-M"_ for time values.

===== Configuration

The default formatting pattern can be set in _Config.groovy_ using the key _jodatime.format.org.joda.time.DateTime_ (or equivalent for other classes). For example:

[source,groovy]
----
jodatime {
	format.org.joda.time.DateTime = "yyyy-MM-dd HH:mm:ss"
	format.org.joda.time.LocalDate = "yyyy-MM-dd"
	format.org.joda.time.LocalTime = "HH:mm:ss"
}
----
