version = projectVersion
group = "org.grails.plugins"

apply plugin: 'groovy'
apply plugin: 'java-library'
apply plugin: 'org.apache.grails.gradle.grails-plugin'
apply plugin: 'org.apache.grails.gradle.grails-gsp'

ext {
    pomArtifactId = 'grails-joda-time'
}

dependencies {
    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'

    // To support databinding to a domain object
    testRuntimeOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    testRuntimeOnly 'org.apache.grails:grails-data-hibernate5'
    testRuntimeOnly 'com.h2database:h2'
    testRuntimeOnly 'com.zaxxer:HikariCP'
    testRuntimeOnly 'org.apache.grails:grails-dependencies-starter-web'

    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
    testImplementation 'org.apache.grails:grails-testing-support-datamapping'
    testImplementation 'org.apache.grails:grails-testing-support-web'
    testImplementation 'org.spockframework:spock-core'
    testImplementation 'org.hamcrest:hamcrest-core'
    testImplementation "org.jodd:jodd-lagarto:$joddVersion"

    api "org.apache.commons:commons-lang3:$commonsVersion"
    api "joda-time:joda-time:$jodaVersion"
}

apply from: rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/test-config.gradle')
apply from: rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')

grails {
    springDependencyManagement = false
}