=== Persistence with Hibernate

In order to persist Joda Time properties with Hibernate you first need to add http://jadira.sourceforge.net/usertype.core/index.html[Usertype Library] to the dependencies to your application's `build.gradle` file:
[source,gradle]
----
implementation "org.jadira.usertype:usertype.core:7.0.0.CR1"
----

==== Adding persistent types to your domain classes

To persist Joda Time properties you can use the Hibernate UserType implementations in the mapping block of your class. For example:

[source,groovy]
----
import org.joda.time.*
import org.jadira.usertype.dateandtime.joda.*

class Person {
    String name
    LocalDate birthdate
    static mapping = {
    	birthdate type: PersistentLocalDate
    }
}
----

This even works with some of the special functionality in Grails. For example fields `dateCreated` and `lastUpdated` in a Grails domain object will be updated automatically by the framework. Such properties do not have to be `java.util.Date` instances the functionality works fine if they are `org.joda.time.DateTime` or other types instead.

==== Adding default type mappings

To avoid having to add type mappings to every single domain class in your application you can create a default mappings block in `application.groovy` that maps Joda Time types to their Hibernate user type implementation. For example:

[source,groovy]
----
grails.gorm.default.mapping = {
	"user-type" type: org.jadira.usertype.dateandtime.joda.PersistentDateTime, class: org.joda.time.DateTime
	"user-type" type: org.jadira.usertype.dateandtime.joda.PersistentLocalDate, class: org.joda.time.LocalDate
	// ... define as many other user type mappings as you need
}
----

The Joda Time plugin can even do this for you so long as you do not already have a `grails.gorm.default.mapping` section in your `Config.groovy` file. Just run `grails install-joda-time-gorm-mappings` and the plugin will add the standard mappings for all supported user types to your `Config.groovy` file.

If you are using the older Joda Time Hibernate library then the package names for the user type classes is `org.joda.time.contrib.hibernate`

==== Multi-column UserTypes

To use multi-column types such as http://jadira.sourceforge.net/apidocs/org/jadira/usertype/dateandtime/joda/PersistentDateTimeWithZone.html[PersistentDateTimeWithZone] you need to include explicit mapping of both column names. For example:

[source,groovy]
----
import org.joda.time.*
import org.jadira.usertype.dateandtime.joda.*

class User {
    DateTime registered
    mapping {
        registered type: PersistentDateTimeWithZone, {
            column name: "registered_timestamp"
            column name: "registered_zone"
        }
    }
}
----

You can use any name you like for the columns.

[WARNING]
====
It is currently not possible to do certain types of criteria query with _DateTime_ properties mapped using _PersistentDateTimeWithZone_ (or any other multi-column Hibernate UserType). Aggregate functions (max, min, avg, count, etc.) in projections will not work on such properties and neither will the _'between'_ criterion.
====

=== Persistence with other GORM implementations
