plugins {
    id 'groovy-gradle-plugin'
}

def versions = new Properties()
file('../gradle.properties').withInputStream {
    versions.load(it)
}

repositories {
//    mavenLocal()
    maven { url = 'https://repo.grails.org/grails/core' }
    mavenCentral()
}

dependencies {
    implementation platform("org.grails:grails-bom:${versions.getProperty('grailsVersion')}")
    implementation 'org.grails:grails-gradle-plugin'
}